sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
script:
  - npm test
  - npm run build
after_success:
  - npx semantic-release@15
branches:
  only:
    - master
